################################################################################
# Automatically-generated file. Do not edit!
################################################################################

CFG_SRCS := 
CP_SRCS := 
CPP_UPPER_SRCS := 
ASM_UPPER_SRCS := 
C++_UPPER_SRCS := 
ASM_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CP_UPPER_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
ABS_SRCS := 
S_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
SRC_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
ASSEMBLER_OBJS := 
CPP_UPPER_DEPS := 
C_UPPER_DEPS := 
CP_DEPS := 
SRC_UPPER_DEPS := 
S_DEPS := 
LINKER_OUTPUT_OUTPUTS := 
ASM_UPPER_DEPS := 
CP_UPPER_DEPS := 
OBJ_DEPS := 
ABS_DEPS := 
CXX_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
SRC_SRCS := 
O_DEPS := 
CXX_UPPER_DEPS := 
CONFIGURATOR_OUTPUTS := 
COMPILER_OBJS := 
C_DEPS := 
CONVERTOR_OUTPUT_OUTPUTS := 
SRC_DEPS := 
CC_DEPS := 
C++_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/states \
src \
src/keyboard \
src/eeprom \
src/config \
src/cnc \
src/cnc/xio \
src/cnc/macros \
src/Nextion \
src/Display \
src/Display/font \
spiffs \
r_vee/src/targets/rx63x \
r_vee/src \
r_usb_hmsc/src \
r_usb_basic/src/driver/peri \
r_usb_basic/src/driver/host \
r_usb_basic/src/driver/comm \
r_usb_basic/src/HW/peri \
r_usb_basic/src/HW/host \
r_usb_basic/src/HW/comm \
r_tmr_rx/src \
r_tfat_driver_rx/src \
r_tfat_driver_rx/src/device/usb_mini \
r_tfat_driver_rx/src/device/usb \
r_tfat_driver_rx/src/device/sdhi \
r_spi_flash/src \
r_sci_async_rx/src \
r_s12ad_rx/src/targets/rx63x \
r_s12ad_rx/src/targets/rx210 \
r_s12ad_rx/src/targets/rx110_rx111 \
r_s12ad_rx/src \
r_rspi_rx/src \
r_mtu_rx/src \
r_lvd_rx/src \
r_flash_loader_rx/src \
r_flash_loader_rx/src/memory \
r_flash_api_rx/src \
r_dtc_rx/src/targets/rx71m \
r_dtc_rx/src/targets/rx64m \
r_dtc_rx/src/targets/rx63n \
r_dtc_rx/src/targets/rx113 \
r_dtc_rx/src/targets/rx111 \
r_dtc_rx/src/targets/rx110 \
r_dtc_rx/src \
r_crc_rx/src \
r_cmt_rx/src \
r_byteq/src \
r_bsp/mcu/rx63n \
r_bsp/mcu/all \
r_bsp/board/MT01 \
fsystem_spi \
fsystem \
FreeRTOS/Source \
FreeRTOS/Source/portable/Renesas/RX600 \
FreeRTOS/Source/portable/MemMang \
.metadata/.plugins/org.eclipse.cdt.make.core \

